spring.application.name=demo
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pbl3}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
payment.bank-transfer-timeout-minutes=30
order.auto-complete-delay-minutes=1440

twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.phone-number=${TWILIO_PHONE_NUMBER:}

# OTP dev behavior
otp.allow-without-sms=true
otp.debug-expose=true

# PayOS Configuration
payment.payo.webhook-secret=${PAYOS_WEBHOOK_SECRET:f27d6bb0af91ca9426bb9962b7333c0662b0a8d7423209329f2c69a5dde556d5}
payment.payo.client-id=${PAYOS_CLIENT_ID:3af9acec-5ff1-4f29-adc0-117052fa8aa6}
payment.payo.api-key=${PAYOS_API_KEY:ef824c9f-be48-441b-a8f1-6f297fd8cfde}
payment.payo.account-number=${PAYOS_ACCOUNT_NUMBER:0963270441}
payment.payo.account-name=TRAN THE TAI
payment.payo.bank-name=MB
payment.payo.return-url=${FRONTEND_URL:http://localhost:5173}/orders
payment.payo.cancel-url=${FRONTEND_URL:http://localhost:5173}/checkout

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:taitran05072006@gmail.com}
spring.mail.password=${MAIL_PASSWORD:jzxoiirhuypffbiu}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
